# Generated by Django 4.1 on 2022-10-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('enrollment_no', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.PositiveIntegerField(max_length=10)),
                ('role', models.CharField(choices=[('des', 'Designer'), ('dev', 'Developer')], default='dev', max_length=3)),
                ('cg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IMG_member',
            fields=[
                ('enrollment_no', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mob', models.PositiveIntegerField(max_length=10)),
                ('role', models.CharField(choices=[('des', 'Designer'), ('dev', 'Developer')], default='dev', max_length=3)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment_season',
            fields=[
                ('year', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role', models.CharField(choices=[('des', 'Designer'), ('dev', 'Developer')], default='dev', max_length=3)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Written Test'), ('i', 'Interview')], default='w', max_length=1)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_year', to='recruitments.recruitment_season')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weightage', models.FloatField()),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_id', to='recruitments.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('mark', models.FloatField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_enrollment_no', to='recruitments.img_member')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='recruitments.section')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.TextField()),
                ('room_no', models.IntegerField()),
                ('status', models.CharField(choices=[('in', 'Inactive'), ('oc', 'Occupied'), ('id', 'Idle')], default='in', max_length=2)),
                ('panelist', models.ManyToManyField(related_name='panelist_enrollment_no', to='recruitments.img_member')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_year', to='recruitments.recruitment_season')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('status', models.CharField(choices=[('NN', 'Not Notified'), ('N', 'Notified'), ('WR', 'In waiting room'), ('IN', 'In Interview'), ('C', 'Complete'), ('AB', 'Absent')], default='NN', max_length=2)),
                ('time_slot', models.CharField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_enrollment_no', to='recruitments.applicant')),
                ('interview_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_id', to='recruitments.interview_panel')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_id', to='recruitments.rounds')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('marks', models.FloatField()),
                ('remarks', models.TextField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_enrollment_no', to='recruitments.applicant')),
                ('queston_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mark_id', to='recruitments.question')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='round_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='recruitments.rounds'),
        ),
    ]
