# Generated by Django 4.1 on 2022-12-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_round',
            name='season_id',
        ),
    ]
